<?php
$TOC = array (
  0 => 
  array (
    0 => 'intro.yaf.php',
    1 => 'Introduction',
  ),
  1 => 
  array (
    0 => 'yaf.setup.php',
    1 => 'Installing/Configuring',
  ),
  2 => 
  array (
    0 => 'yaf.constants.php',
    1 => 'Predefined Constants',
  ),
  3 => 
  array (
    0 => 'yaf.tutorials.php',
    1 => 'Examples',
  ),
  4 => 
  array (
    0 => 'yaf.appconfig.php',
    1 => 'Application Configuration',
  ),
  5 => 
  array (
    0 => 'class.yaf-application.php',
    1 => 'Yaf_Application',
  ),
  6 => 
  array (
    0 => 'class.yaf-bootstrap-abstract.php',
    1 => 'Yaf_Bootstrap_Abstract',
  ),
  7 => 
  array (
    0 => 'class.yaf-dispatcher.php',
    1 => 'Yaf_Dispatcher',
  ),
  8 => 
  array (
    0 => 'class.yaf-config-abstract.php',
    1 => 'Yaf_Config_Abstract',
  ),
  9 => 
  array (
    0 => 'class.yaf-config-ini.php',
    1 => 'Yaf_Config_Ini',
  ),
  10 => 
  array (
    0 => 'class.yaf-config-simple.php',
    1 => 'Yaf_Config_Simple',
  ),
  11 => 
  array (
    0 => 'class.yaf-controller-abstract.php',
    1 => 'Yaf_Controller_Abstract',
  ),
  12 => 
  array (
    0 => 'class.yaf-action-abstract.php',
    1 => 'Yaf_Action_Abstract',
  ),
  13 => 
  array (
    0 => 'class.yaf-view-interface.php',
    1 => 'Yaf_View_Interface',
  ),
  14 => 
  array (
    0 => 'class.yaf-view-simple.php',
    1 => 'Yaf_View_Simple',
  ),
  15 => 
  array (
    0 => 'class.yaf-loader.php',
    1 => 'Yaf_Loader',
  ),
  16 => 
  array (
    0 => 'class.yaf-plugin-abstract.php',
    1 => 'Yaf_Plugin_Abstract',
  ),
  17 => 
  array (
    0 => 'class.yaf-registry.php',
    1 => 'Yaf_Registry',
  ),
  18 => 
  array (
    0 => 'class.yaf-request-abstract.php',
    1 => 'Yaf_Request_Abstract',
  ),
  19 => 
  array (
    0 => 'class.yaf-request-http.php',
    1 => 'Yaf_Request_Http',
  ),
  20 => 
  array (
    0 => 'class.yaf-request-simple.php',
    1 => 'Yaf_Request_Simple',
  ),
  21 => 
  array (
    0 => 'class.yaf-response-abstract.php',
    1 => 'Yaf_Response_Abstract',
  ),
  22 => 
  array (
    0 => 'class.yaf-route-interface.php',
    1 => 'Yaf_Route_Interface',
  ),
  23 => 
  array (
    0 => 'class.yaf-route-map.php',
    1 => 'Yaf_Route_Map',
  ),
  24 => 
  array (
    0 => 'class.yaf-route-regex.php',
    1 => 'Yaf_Route_Regex',
  ),
  25 => 
  array (
    0 => 'class.yaf-route-rewrite.php',
    1 => 'Yaf_Route_Rewrite',
  ),
  26 => 
  array (
    0 => 'class.yaf-router.php',
    1 => 'Yaf_Router',
  ),
  27 => 
  array (
    0 => 'class.yaf-route-simple.php',
    1 => 'Yaf_Route_Simple',
  ),
  28 => 
  array (
    0 => 'class.yaf-route-static.php',
    1 => 'Yaf_Route_Static',
  ),
  29 => 
  array (
    0 => 'class.yaf-route-supervar.php',
    1 => 'Yaf_Route_Supervar',
  ),
  30 => 
  array (
    0 => 'class.yaf-session.php',
    1 => 'Yaf_Session',
  ),
  31 => 
  array (
    0 => 'class.yaf-exception.php',
    1 => 'Yaf_Exception',
  ),
  32 => 
  array (
    0 => 'class.yaf-exception-typeerror.php',
    1 => 'Yaf_Exception_TypeError',
  ),
  33 => 
  array (
    0 => 'class.yaf-exception-startuperror.php',
    1 => 'Yaf_Exception_StartupError',
  ),
  34 => 
  array (
    0 => 'class.yaf-exception-dispatchfailed.php',
    1 => 'Yaf_Exception_DispatchFailed',
  ),
  35 => 
  array (
    0 => 'class.yaf-exception-routerfailed.php',
    1 => 'Yaf_Exception_RouterFailed',
  ),
  36 => 
  array (
    0 => 'class.yaf-exception-loadfailed.php',
    1 => 'Yaf_Exception_LoadFailed',
  ),
  37 => 
  array (
    0 => 'class.yaf-exception-loadfailed-module.php',
    1 => 'Yaf_Exception_LoadFailed_Module',
  ),
  38 => 
  array (
    0 => 'class.yaf-exception-loadfailed-controller.php',
    1 => 'Yaf_Exception_LoadFailed_Controller',
  ),
  39 => 
  array (
    0 => 'class.yaf-exception-loadfailed-action.php',
    1 => 'Yaf_Exception_LoadFailed_Action',
  ),
  40 => 
  array (
    0 => 'class.yaf-exception-loadfailed-view.php',
    1 => 'Yaf_Exception_LoadFailed_View',
  ),
);
$PARENTS = array (
);