<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-request-http.clone.php',
    1 => 'Yaf_Request_Http::__clone',
  ),
  1 => 
  array (
    0 => 'yaf-request-http.construct.php',
    1 => 'Yaf_Request_Http::__construct',
  ),
  2 => 
  array (
    0 => 'yaf-request-http.get.php',
    1 => 'Yaf_Request_Http::get',
  ),
  3 => 
  array (
    0 => 'yaf-request-http.getcookie.php',
    1 => 'Yaf_Request_Http::getCookie',
  ),
  4 => 
  array (
    0 => 'yaf-request-http.getfiles.php',
    1 => 'Yaf_Request_Http::getFiles',
  ),
  5 => 
  array (
    0 => 'yaf-request-http.getpost.php',
    1 => 'Yaf_Request_Http::getPost',
  ),
  6 => 
  array (
    0 => 'yaf-request-http.getquery.php',
    1 => 'Yaf_Request_Http::getQuery',
  ),
  7 => 
  array (
    0 => 'yaf-request-http.getrequest.php',
    1 => 'Yaf_Request_Http::getRequest',
  ),
  8 => 
  array (
    0 => 'yaf-request-http.isxmlhttprequest.php',
    1 => 'Yaf_Request_Http::isXmlHttpRequest',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);