<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-response-abstract.appendbody.php',
    1 => 'Yaf_Response_Abstract::appendBody',
  ),
  1 => 
  array (
    0 => 'yaf-response-abstract.clearbody.php',
    1 => 'Yaf_Response_Abstract::clearBody',
  ),
  2 => 
  array (
    0 => 'yaf-response-abstract.clearheaders.php',
    1 => 'Yaf_Response_Abstract::clearHeaders',
  ),
  3 => 
  array (
    0 => 'yaf-response-abstract.clone.php',
    1 => 'Yaf_Response_Abstract::__clone',
  ),
  4 => 
  array (
    0 => 'yaf-response-abstract.construct.php',
    1 => 'Yaf_Response_Abstract::__construct',
  ),
  5 => 
  array (
    0 => 'yaf-response-abstract.destruct.php',
    1 => 'Yaf_Response_Abstract::__destruct',
  ),
  6 => 
  array (
    0 => 'yaf-response-abstract.getbody.php',
    1 => 'Yaf_Response_Abstract::getBody',
  ),
  7 => 
  array (
    0 => 'yaf-response-abstract.getheader.php',
    1 => 'Yaf_Response_Abstract::getHeader',
  ),
  8 => 
  array (
    0 => 'yaf-response-abstract.prependbody.php',
    1 => 'Yaf_Response_Abstract::prependBody',
  ),
  9 => 
  array (
    0 => 'yaf-response-abstract.response.php',
    1 => 'Yaf_Response_Abstract::response',
  ),
  10 => 
  array (
    0 => 'yaf-response-abstract.setallheaders.php',
    1 => 'Yaf_Response_Abstract::setAllHeaders',
  ),
  11 => 
  array (
    0 => 'yaf-response-abstract.setbody.php',
    1 => 'Yaf_Response_Abstract::setBody',
  ),
  12 => 
  array (
    0 => 'yaf-response-abstract.setheader.php',
    1 => 'Yaf_Response_Abstract::setHeader',
  ),
  13 => 
  array (
    0 => 'yaf-response-abstract.setredirect.php',
    1 => 'Yaf_Response_Abstract::setRedirect',
  ),
  14 => 
  array (
    0 => 'yaf-response-abstract.tostring.php',
    1 => 'Yaf_Response_Abstract::__toString',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);