<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-loader.autoload.php',
    1 => 'Yaf_Loader::autoload',
  ),
  1 => 
  array (
    0 => 'yaf-loader.clearlocalnamespace.php',
    1 => 'Yaf_Loader::clearLocalNamespace',
  ),
  2 => 
  array (
    0 => 'yaf-loader.clone.php',
    1 => 'Yaf_Loader::__clone',
  ),
  3 => 
  array (
    0 => 'yaf-loader.construct.php',
    1 => 'Yaf_Loader::__construct',
  ),
  4 => 
  array (
    0 => 'yaf-loader.getinstance.php',
    1 => 'Yaf_Loader::getInstance',
  ),
  5 => 
  array (
    0 => 'yaf-loader.getlibrarypath.php',
    1 => 'Yaf_Loader::getLibraryPath',
  ),
  6 => 
  array (
    0 => 'yaf-loader.getlocalnamespace.php',
    1 => 'Yaf_Loader::getLocalNamespace',
  ),
  7 => 
  array (
    0 => 'yaf-loader.import.php',
    1 => 'Yaf_Loader::import',
  ),
  8 => 
  array (
    0 => 'yaf-loader.islocalname.php',
    1 => 'Yaf_Loader::isLocalName',
  ),
  9 => 
  array (
    0 => 'yaf-loader.registerlocalnamespace.php',
    1 => 'Yaf_Loader::registerLocalNamespace',
  ),
  10 => 
  array (
    0 => 'yaf-loader.setlibrarypath.php',
    1 => 'Yaf_Loader::setLibraryPath',
  ),
  11 => 
  array (
    0 => 'yaf-loader.sleep.php',
    1 => 'Yaf_Loader::__sleep',
  ),
  12 => 
  array (
    0 => 'yaf-loader.wakeup.php',
    1 => 'Yaf_Loader::__wakeup',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);