<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-config-ini.construct.php',
    1 => 'Yaf_Config_Ini::__construct',
  ),
  1 => 
  array (
    0 => 'yaf-config-ini.count.php',
    1 => 'Yaf_Config_Ini::count',
  ),
  2 => 
  array (
    0 => 'yaf-config-ini.current.php',
    1 => 'Yaf_Config_Ini::current',
  ),
  3 => 
  array (
    0 => 'yaf-config-ini.get.php',
    1 => 'Yaf_Config_Ini::__get',
  ),
  4 => 
  array (
    0 => 'yaf-config-ini.isset.php',
    1 => 'Yaf_Config_Ini::__isset',
  ),
  5 => 
  array (
    0 => 'yaf-config-ini.key.php',
    1 => 'Yaf_Config_Ini::key',
  ),
  6 => 
  array (
    0 => 'yaf-config-ini.next.php',
    1 => 'Yaf_Config_Ini::next',
  ),
  7 => 
  array (
    0 => 'yaf-config-ini.offsetexists.php',
    1 => 'Yaf_Config_Ini::offsetExists',
  ),
  8 => 
  array (
    0 => 'yaf-config-ini.offsetget.php',
    1 => 'Yaf_Config_Ini::offsetGet',
  ),
  9 => 
  array (
    0 => 'yaf-config-ini.offsetset.php',
    1 => 'Yaf_Config_Ini::offsetSet',
  ),
  10 => 
  array (
    0 => 'yaf-config-ini.offsetunset.php',
    1 => 'Yaf_Config_Ini::offsetUnset',
  ),
  11 => 
  array (
    0 => 'yaf-config-ini.readonly.php',
    1 => 'Yaf_Config_Ini::readonly',
  ),
  12 => 
  array (
    0 => 'yaf-config-ini.rewind.php',
    1 => 'Yaf_Config_Ini::rewind',
  ),
  13 => 
  array (
    0 => 'yaf-config-ini.set.php',
    1 => 'Yaf_Config_Ini::__set',
  ),
  14 => 
  array (
    0 => 'yaf-config-ini.toarray.php',
    1 => 'Yaf_Config_Ini::toArray',
  ),
  15 => 
  array (
    0 => 'yaf-config-ini.valid.php',
    1 => 'Yaf_Config_Ini::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);