<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-dispatcher.autorender.php',
    1 => 'Yaf_Dispatcher::autoRender',
  ),
  1 => 
  array (
    0 => 'yaf-dispatcher.catchexception.php',
    1 => 'Yaf_Dispatcher::catchException',
  ),
  2 => 
  array (
    0 => 'yaf-dispatcher.clone.php',
    1 => 'Yaf_Dispatcher::__clone',
  ),
  3 => 
  array (
    0 => 'yaf-dispatcher.construct.php',
    1 => 'Yaf_Dispatcher::__construct',
  ),
  4 => 
  array (
    0 => 'yaf-dispatcher.disableview.php',
    1 => 'Yaf_Dispatcher::disableView',
  ),
  5 => 
  array (
    0 => 'yaf-dispatcher.dispatch.php',
    1 => 'Yaf_Dispatcher::dispatch',
  ),
  6 => 
  array (
    0 => 'yaf-dispatcher.enableview.php',
    1 => 'Yaf_Dispatcher::enableView',
  ),
  7 => 
  array (
    0 => 'yaf-dispatcher.flushinstantly.php',
    1 => 'Yaf_Dispatcher::flushInstantly',
  ),
  8 => 
  array (
    0 => 'yaf-dispatcher.getapplication.php',
    1 => 'Yaf_Dispatcher::getApplication',
  ),
  9 => 
  array (
    0 => 'yaf-dispatcher.getinstance.php',
    1 => 'Yaf_Dispatcher::getInstance',
  ),
  10 => 
  array (
    0 => 'yaf-dispatcher.getrequest.php',
    1 => 'Yaf_Dispatcher::getRequest',
  ),
  11 => 
  array (
    0 => 'yaf-dispatcher.getrouter.php',
    1 => 'Yaf_Dispatcher::getRouter',
  ),
  12 => 
  array (
    0 => 'yaf-dispatcher.initview.php',
    1 => 'Yaf_Dispatcher::initView',
  ),
  13 => 
  array (
    0 => 'yaf-dispatcher.registerplugin.php',
    1 => 'Yaf_Dispatcher::registerPlugin',
  ),
  14 => 
  array (
    0 => 'yaf-dispatcher.returnresponse.php',
    1 => 'Yaf_Dispatcher::returnResponse',
  ),
  15 => 
  array (
    0 => 'yaf-dispatcher.setdefaultaction.php',
    1 => 'Yaf_Dispatcher::setDefaultAction',
  ),
  16 => 
  array (
    0 => 'yaf-dispatcher.setdefaultcontroller.php',
    1 => 'Yaf_Dispatcher::setDefaultController',
  ),
  17 => 
  array (
    0 => 'yaf-dispatcher.setdefaultmodule.php',
    1 => 'Yaf_Dispatcher::setDefaultModule',
  ),
  18 => 
  array (
    0 => 'yaf-dispatcher.seterrorhandler.php',
    1 => 'Yaf_Dispatcher::setErrorHandler',
  ),
  19 => 
  array (
    0 => 'yaf-dispatcher.setrequest.php',
    1 => 'Yaf_Dispatcher::setRequest',
  ),
  20 => 
  array (
    0 => 'yaf-dispatcher.setview.php',
    1 => 'Yaf_Dispatcher::setView',
  ),
  21 => 
  array (
    0 => 'yaf-dispatcher.sleep.php',
    1 => 'Yaf_Dispatcher::__sleep',
  ),
  22 => 
  array (
    0 => 'yaf-dispatcher.throwexception.php',
    1 => 'Yaf_Dispatcher::throwException',
  ),
  23 => 
  array (
    0 => 'yaf-dispatcher.wakeup.php',
    1 => 'Yaf_Dispatcher::__wakeup',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);