<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-route-map.assemble.php',
    1 => 'Yaf_Route_Map::assemble',
  ),
  1 => 
  array (
    0 => 'yaf-route-map.construct.php',
    1 => 'Yaf_Route_Map::__construct',
  ),
  2 => 
  array (
    0 => 'yaf-route-map.route.php',
    1 => 'Yaf_Route_Map::route',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);