<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-view-simple.assign.php',
    1 => 'Yaf_View_Simple::assign',
  ),
  1 => 
  array (
    0 => 'yaf-view-simple.assignref.php',
    1 => 'Yaf_View_Simple::assignRef',
  ),
  2 => 
  array (
    0 => 'yaf-view-simple.clear.php',
    1 => 'Yaf_View_Simple::clear',
  ),
  3 => 
  array (
    0 => 'yaf-view-simple.construct.php',
    1 => 'Yaf_View_Simple::__construct',
  ),
  4 => 
  array (
    0 => 'yaf-view-simple.display.php',
    1 => 'Yaf_View_Simple::display',
  ),
  5 => 
  array (
    0 => 'yaf-view-simple.eval.php',
    1 => 'Yaf_View_Simple::eval',
  ),
  6 => 
  array (
    0 => 'yaf-view-simple.get.php',
    1 => 'Yaf_View_Simple::__get',
  ),
  7 => 
  array (
    0 => 'yaf-view-simple.getscriptpath.php',
    1 => 'Yaf_View_Simple::getScriptPath',
  ),
  8 => 
  array (
    0 => 'yaf-view-simple.isset.php',
    1 => 'Yaf_View_Simple::__isset',
  ),
  9 => 
  array (
    0 => 'yaf-view-simple.render.php',
    1 => 'Yaf_View_Simple::render',
  ),
  10 => 
  array (
    0 => 'yaf-view-simple.set.php',
    1 => 'Yaf_View_Simple::__set',
  ),
  11 => 
  array (
    0 => 'yaf-view-simple.setscriptpath.php',
    1 => 'Yaf_View_Simple::setScriptPath',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);