<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-config-abstract.get.php',
    1 => 'Yaf_Config_Abstract::get',
  ),
  1 => 
  array (
    0 => 'yaf-config-abstract.readonly.php',
    1 => 'Yaf_Config_Abstract::readonly',
  ),
  2 => 
  array (
    0 => 'yaf-config-abstract.set.php',
    1 => 'Yaf_Config_Abstract::set',
  ),
  3 => 
  array (
    0 => 'yaf-config-abstract.toarray.php',
    1 => 'Yaf_Config_Abstract::toArray',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);