<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-request-simple.clone.php',
    1 => 'Yaf_Request_Simple::__clone',
  ),
  1 => 
  array (
    0 => 'yaf-request-simple.construct.php',
    1 => 'Yaf_Request_Simple::__construct',
  ),
  2 => 
  array (
    0 => 'yaf-request-simple.get.php',
    1 => 'Yaf_Request_Simple::get',
  ),
  3 => 
  array (
    0 => 'yaf-request-simple.getcookie.php',
    1 => 'Yaf_Request_Simple::getCookie',
  ),
  4 => 
  array (
    0 => 'yaf-request-simple.getfiles.php',
    1 => 'Yaf_Request_Simple::getFiles',
  ),
  5 => 
  array (
    0 => 'yaf-request-simple.getpost.php',
    1 => 'Yaf_Request_Simple::getPost',
  ),
  6 => 
  array (
    0 => 'yaf-request-simple.getquery.php',
    1 => 'Yaf_Request_Simple::getQuery',
  ),
  7 => 
  array (
    0 => 'yaf-request-simple.getrequest.php',
    1 => 'Yaf_Request_Simple::getRequest',
  ),
  8 => 
  array (
    0 => 'yaf-request-simple.isxmlhttprequest.php',
    1 => 'Yaf_Request_Simple::isXmlHttpRequest',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);