<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-router.addconfig.php',
    1 => 'Yaf_Router::addConfig',
  ),
  1 => 
  array (
    0 => 'yaf-router.addroute.php',
    1 => 'Yaf_Router::addRoute',
  ),
  2 => 
  array (
    0 => 'yaf-router.construct.php',
    1 => 'Yaf_Router::__construct',
  ),
  3 => 
  array (
    0 => 'yaf-router.getcurrentroute.php',
    1 => 'Yaf_Router::getCurrentRoute',
  ),
  4 => 
  array (
    0 => 'yaf-router.getroute.php',
    1 => 'Yaf_Router::getRoute',
  ),
  5 => 
  array (
    0 => 'yaf-router.getroutes.php',
    1 => 'Yaf_Router::getRoutes',
  ),
  6 => 
  array (
    0 => 'yaf-router.route.php',
    1 => 'Yaf_Router::route',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);