<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-route-rewrite.assemble.php',
    1 => 'Yaf_Route_Rewrite::assemble',
  ),
  1 => 
  array (
    0 => 'yaf-route-rewrite.construct.php',
    1 => 'Yaf_Route_Rewrite::__construct',
  ),
  2 => 
  array (
    0 => 'yaf-route-rewrite.route.php',
    1 => 'Yaf_Route_Rewrite::route',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);