<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-controller-abstract.clone.php',
    1 => 'Yaf_Controller_Abstract::__clone',
  ),
  1 => 
  array (
    0 => 'yaf-controller-abstract.construct.php',
    1 => 'Yaf_Controller_Abstract::__construct',
  ),
  2 => 
  array (
    0 => 'yaf-controller-abstract.display.php',
    1 => 'Yaf_Controller_Abstract::display',
  ),
  3 => 
  array (
    0 => 'yaf-controller-abstract.forward.php',
    1 => 'Yaf_Controller_Abstract::forward',
  ),
  4 => 
  array (
    0 => 'yaf-controller-abstract.getinvokearg.php',
    1 => 'Yaf_Controller_Abstract::getInvokeArg',
  ),
  5 => 
  array (
    0 => 'yaf-controller-abstract.getinvokeargs.php',
    1 => 'Yaf_Controller_Abstract::getInvokeArgs',
  ),
  6 => 
  array (
    0 => 'yaf-controller-abstract.getmodulename.php',
    1 => 'Yaf_Controller_Abstract::getModuleName',
  ),
  7 => 
  array (
    0 => 'yaf-controller-abstract.getrequest.php',
    1 => 'Yaf_Controller_Abstract::getRequest',
  ),
  8 => 
  array (
    0 => 'yaf-controller-abstract.getresponse.php',
    1 => 'Yaf_Controller_Abstract::getResponse',
  ),
  9 => 
  array (
    0 => 'yaf-controller-abstract.getview.php',
    1 => 'Yaf_Controller_Abstract::getView',
  ),
  10 => 
  array (
    0 => 'yaf-controller-abstract.getviewpath.php',
    1 => 'Yaf_Controller_Abstract::getViewpath',
  ),
  11 => 
  array (
    0 => 'yaf-controller-abstract.init.php',
    1 => 'Yaf_Controller_Abstract::init',
  ),
  12 => 
  array (
    0 => 'yaf-controller-abstract.initview.php',
    1 => 'Yaf_Controller_Abstract::initView',
  ),
  13 => 
  array (
    0 => 'yaf-controller-abstract.redirect.php',
    1 => 'Yaf_Controller_Abstract::redirect',
  ),
  14 => 
  array (
    0 => 'yaf-controller-abstract.render.php',
    1 => 'Yaf_Controller_Abstract::render',
  ),
  15 => 
  array (
    0 => 'yaf-controller-abstract.setviewpath.php',
    1 => 'Yaf_Controller_Abstract::setViewpath',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);