<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-registry.clone.php',
    1 => 'Yaf_Registry::__clone',
  ),
  1 => 
  array (
    0 => 'yaf-registry.construct.php',
    1 => 'Yaf_Registry::__construct',
  ),
  2 => 
  array (
    0 => 'yaf-registry.del.php',
    1 => 'Yaf_Registry::del',
  ),
  3 => 
  array (
    0 => 'yaf-registry.get.php',
    1 => 'Yaf_Registry::get',
  ),
  4 => 
  array (
    0 => 'yaf-registry.has.php',
    1 => 'Yaf_Registry::has',
  ),
  5 => 
  array (
    0 => 'yaf-registry.set.php',
    1 => 'Yaf_Registry::set',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);