<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-application.app.php',
    1 => 'Yaf_Application::app',
  ),
  1 => 
  array (
    0 => 'yaf-application.bootstrap.php',
    1 => 'Yaf_Application::bootstrap',
  ),
  2 => 
  array (
    0 => 'yaf-application.clearlasterror.php',
    1 => 'Yaf_Application::clearLastError',
  ),
  3 => 
  array (
    0 => 'yaf-application.clone.php',
    1 => 'Yaf_Application::__clone',
  ),
  4 => 
  array (
    0 => 'yaf-application.construct.php',
    1 => 'Yaf_Application::__construct',
  ),
  5 => 
  array (
    0 => 'yaf-application.destruct.php',
    1 => 'Yaf_Application::__destruct',
  ),
  6 => 
  array (
    0 => 'yaf-application.environ.php',
    1 => 'Yaf_Application::environ',
  ),
  7 => 
  array (
    0 => 'yaf-application.execute.php',
    1 => 'Yaf_Application::execute',
  ),
  8 => 
  array (
    0 => 'yaf-application.getappdirectory.php',
    1 => 'Yaf_Application::getAppDirectory',
  ),
  9 => 
  array (
    0 => 'yaf-application.getconfig.php',
    1 => 'Yaf_Application::getConfig',
  ),
  10 => 
  array (
    0 => 'yaf-application.getdispatcher.php',
    1 => 'Yaf_Application::getDispatcher',
  ),
  11 => 
  array (
    0 => 'yaf-application.getlasterrormsg.php',
    1 => 'Yaf_Application::getLastErrorMsg',
  ),
  12 => 
  array (
    0 => 'yaf-application.getlasterrorno.php',
    1 => 'Yaf_Application::getLastErrorNo',
  ),
  13 => 
  array (
    0 => 'yaf-application.getmodules.php',
    1 => 'Yaf_Application::getModules',
  ),
  14 => 
  array (
    0 => 'yaf-application.run.php',
    1 => 'Yaf_Application::run',
  ),
  15 => 
  array (
    0 => 'yaf-application.setappdirectory.php',
    1 => 'Yaf_Application::setAppDirectory',
  ),
  16 => 
  array (
    0 => 'yaf-application.sleep.php',
    1 => 'Yaf_Application::__sleep',
  ),
  17 => 
  array (
    0 => 'yaf-application.wakeup.php',
    1 => 'Yaf_Application::__wakeup',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);