<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf.requirements.php',
    1 => 'Requirements',
  ),
  1 => 
  array (
    0 => 'yaf.installation.php',
    1 => 'Installation',
  ),
  2 => 
  array (
    0 => 'yaf.configuration.php',
    1 => 'Runtime Configuration',
  ),
  3 => 
  array (
    0 => 'yaf.resources.php',
    1 => 'Resource Types',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);