<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-route-supervar.assemble.php',
    1 => 'Yaf_Route_Supervar::assemble',
  ),
  1 => 
  array (
    0 => 'yaf-route-supervar.construct.php',
    1 => 'Yaf_Route_Supervar::__construct',
  ),
  2 => 
  array (
    0 => 'yaf-route-supervar.route.php',
    1 => 'Yaf_Route_Supervar::route',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);