<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-session.clone.php',
    1 => 'Yaf_Session::__clone',
  ),
  1 => 
  array (
    0 => 'yaf-session.construct.php',
    1 => 'Yaf_Session::__construct',
  ),
  2 => 
  array (
    0 => 'yaf-session.count.php',
    1 => 'Yaf_Session::count',
  ),
  3 => 
  array (
    0 => 'yaf-session.current.php',
    1 => 'Yaf_Session::current',
  ),
  4 => 
  array (
    0 => 'yaf-session.del.php',
    1 => 'Yaf_Session::del',
  ),
  5 => 
  array (
    0 => 'yaf-session.get.php',
    1 => 'Yaf_Session::__get',
  ),
  6 => 
  array (
    0 => 'yaf-session.getinstance.php',
    1 => 'Yaf_Session::getInstance',
  ),
  7 => 
  array (
    0 => 'yaf-session.has.php',
    1 => 'Yaf_Session::has',
  ),
  8 => 
  array (
    0 => 'yaf-session.isset.php',
    1 => 'Yaf_Session::__isset',
  ),
  9 => 
  array (
    0 => 'yaf-session.key.php',
    1 => 'Yaf_Session::key',
  ),
  10 => 
  array (
    0 => 'yaf-session.next.php',
    1 => 'Yaf_Session::next',
  ),
  11 => 
  array (
    0 => 'yaf-session.offsetexists.php',
    1 => 'Yaf_Session::offsetExists',
  ),
  12 => 
  array (
    0 => 'yaf-session.offsetget.php',
    1 => 'Yaf_Session::offsetGet',
  ),
  13 => 
  array (
    0 => 'yaf-session.offsetset.php',
    1 => 'Yaf_Session::offsetSet',
  ),
  14 => 
  array (
    0 => 'yaf-session.offsetunset.php',
    1 => 'Yaf_Session::offsetUnset',
  ),
  15 => 
  array (
    0 => 'yaf-session.rewind.php',
    1 => 'Yaf_Session::rewind',
  ),
  16 => 
  array (
    0 => 'yaf-session.set.php',
    1 => 'Yaf_Session::__set',
  ),
  17 => 
  array (
    0 => 'yaf-session.sleep.php',
    1 => 'Yaf_Session::__sleep',
  ),
  18 => 
  array (
    0 => 'yaf-session.start.php',
    1 => 'Yaf_Session::start',
  ),
  19 => 
  array (
    0 => 'yaf-session.unset.php',
    1 => 'Yaf_Session::__unset',
  ),
  20 => 
  array (
    0 => 'yaf-session.valid.php',
    1 => 'Yaf_Session::valid',
  ),
  21 => 
  array (
    0 => 'yaf-session.wakeup.php',
    1 => 'Yaf_Session::__wakeup',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);