<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-route-regex.assemble.php',
    1 => 'Yaf_Route_Regex::assemble',
  ),
  1 => 
  array (
    0 => 'yaf-route-regex.construct.php',
    1 => 'Yaf_Route_Regex::__construct',
  ),
  2 => 
  array (
    0 => 'yaf-route-regex.route.php',
    1 => 'Yaf_Route_Regex::route',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);