<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-route-static.assemble.php',
    1 => 'Yaf_Route_Static::assemble',
  ),
  1 => 
  array (
    0 => 'yaf-route-static.match.php',
    1 => 'Yaf_Route_Static::match',
  ),
  2 => 
  array (
    0 => 'yaf-route-static.route.php',
    1 => 'Yaf_Route_Static::route',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);