<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-config-simple.construct.php',
    1 => 'Yaf_Config_Simple::__construct',
  ),
  1 => 
  array (
    0 => 'yaf-config-simple.count.php',
    1 => 'Yaf_Config_Simple::count',
  ),
  2 => 
  array (
    0 => 'yaf-config-simple.current.php',
    1 => 'Yaf_Config_Simple::current',
  ),
  3 => 
  array (
    0 => 'yaf-config-simple.get.php',
    1 => 'Yaf_Config_Simple::__get',
  ),
  4 => 
  array (
    0 => 'yaf-config-simple.isset.php',
    1 => 'Yaf_Config_Simple::__isset',
  ),
  5 => 
  array (
    0 => 'yaf-config-simple.key.php',
    1 => 'Yaf_Config_Simple::key',
  ),
  6 => 
  array (
    0 => 'yaf-config-simple.next.php',
    1 => 'Yaf_Config_Simple::next',
  ),
  7 => 
  array (
    0 => 'yaf-config-simple.offsetexists.php',
    1 => 'Yaf_Config_Simple::offsetExists',
  ),
  8 => 
  array (
    0 => 'yaf-config-simple.offsetget.php',
    1 => 'Yaf_Config_Simple::offsetGet',
  ),
  9 => 
  array (
    0 => 'yaf-config-simple.offsetset.php',
    1 => 'Yaf_Config_Simple::offsetSet',
  ),
  10 => 
  array (
    0 => 'yaf-config-simple.offsetunset.php',
    1 => 'Yaf_Config_Simple::offsetUnset',
  ),
  11 => 
  array (
    0 => 'yaf-config-simple.readonly.php',
    1 => 'Yaf_Config_Simple::readonly',
  ),
  12 => 
  array (
    0 => 'yaf-config-simple.rewind.php',
    1 => 'Yaf_Config_Simple::rewind',
  ),
  13 => 
  array (
    0 => 'yaf-config-simple.set.php',
    1 => 'Yaf_Config_Simple::__set',
  ),
  14 => 
  array (
    0 => 'yaf-config-simple.toarray.php',
    1 => 'Yaf_Config_Simple::toArray',
  ),
  15 => 
  array (
    0 => 'yaf-config-simple.valid.php',
    1 => 'Yaf_Config_Simple::valid',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);