<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-plugin-abstract.dispatchloopshutdown.php',
    1 => 'Yaf_Plugin_Abstract::dispatchLoopShutdown',
  ),
  1 => 
  array (
    0 => 'yaf-plugin-abstract.dispatchloopstartup.php',
    1 => 'Yaf_Plugin_Abstract::dispatchLoopStartup',
  ),
  2 => 
  array (
    0 => 'yaf-plugin-abstract.postdispatch.php',
    1 => 'Yaf_Plugin_Abstract::postDispatch',
  ),
  3 => 
  array (
    0 => 'yaf-plugin-abstract.predispatch.php',
    1 => 'Yaf_Plugin_Abstract::preDispatch',
  ),
  4 => 
  array (
    0 => 'yaf-plugin-abstract.preresponse.php',
    1 => 'Yaf_Plugin_Abstract::preResponse',
  ),
  5 => 
  array (
    0 => 'yaf-plugin-abstract.routershutdown.php',
    1 => 'Yaf_Plugin_Abstract::routerShutdown',
  ),
  6 => 
  array (
    0 => 'yaf-plugin-abstract.routerstartup.php',
    1 => 'Yaf_Plugin_Abstract::routerStartup',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);