<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-view-interface.assign.php',
    1 => 'Yaf_View_Interface::assign',
  ),
  1 => 
  array (
    0 => 'yaf-view-interface.display.php',
    1 => 'Yaf_View_Interface::display',
  ),
  2 => 
  array (
    0 => 'yaf-view-interface.getscriptpath.php',
    1 => 'Yaf_View_Interface::getScriptPath',
  ),
  3 => 
  array (
    0 => 'yaf-view-interface.render.php',
    1 => 'Yaf_View_Interface::render',
  ),
  4 => 
  array (
    0 => 'yaf-view-interface.setscriptpath.php',
    1 => 'Yaf_View_Interface::setScriptPath',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);