<?php
$TOC = array (
  0 => 
  array (
    0 => 'yaf-request-abstract.getactionname.php',
    1 => 'Yaf_Request_Abstract::getActionName',
  ),
  1 => 
  array (
    0 => 'yaf-request-abstract.getbaseuri.php',
    1 => 'Yaf_Request_Abstract::getBaseUri',
  ),
  2 => 
  array (
    0 => 'yaf-request-abstract.getcontrollername.php',
    1 => 'Yaf_Request_Abstract::getControllerName',
  ),
  3 => 
  array (
    0 => 'yaf-request-abstract.getenv.php',
    1 => 'Yaf_Request_Abstract::getEnv',
  ),
  4 => 
  array (
    0 => 'yaf-request-abstract.getexception.php',
    1 => 'Yaf_Request_Abstract::getException',
  ),
  5 => 
  array (
    0 => 'yaf-request-abstract.getlanguage.php',
    1 => 'Yaf_Request_Abstract::getLanguage',
  ),
  6 => 
  array (
    0 => 'yaf-request-abstract.getmethod.php',
    1 => 'Yaf_Request_Abstract::getMethod',
  ),
  7 => 
  array (
    0 => 'yaf-request-abstract.getmodulename.php',
    1 => 'Yaf_Request_Abstract::getModuleName',
  ),
  8 => 
  array (
    0 => 'yaf-request-abstract.getparam.php',
    1 => 'Yaf_Request_Abstract::getParam',
  ),
  9 => 
  array (
    0 => 'yaf-request-abstract.getparams.php',
    1 => 'Yaf_Request_Abstract::getParams',
  ),
  10 => 
  array (
    0 => 'yaf-request-abstract.getrequesturi.php',
    1 => 'Yaf_Request_Abstract::getRequestUri',
  ),
  11 => 
  array (
    0 => 'yaf-request-abstract.getserver.php',
    1 => 'Yaf_Request_Abstract::getServer',
  ),
  12 => 
  array (
    0 => 'yaf-request-abstract.iscli.php',
    1 => 'Yaf_Request_Abstract::isCli',
  ),
  13 => 
  array (
    0 => 'yaf-request-abstract.isdispatched.php',
    1 => 'Yaf_Request_Abstract::isDispatched',
  ),
  14 => 
  array (
    0 => 'yaf-request-abstract.isget.php',
    1 => 'Yaf_Request_Abstract::isGet',
  ),
  15 => 
  array (
    0 => 'yaf-request-abstract.ishead.php',
    1 => 'Yaf_Request_Abstract::isHead',
  ),
  16 => 
  array (
    0 => 'yaf-request-abstract.isoptions.php',
    1 => 'Yaf_Request_Abstract::isOptions',
  ),
  17 => 
  array (
    0 => 'yaf-request-abstract.ispost.php',
    1 => 'Yaf_Request_Abstract::isPost',
  ),
  18 => 
  array (
    0 => 'yaf-request-abstract.isput.php',
    1 => 'Yaf_Request_Abstract::isPut',
  ),
  19 => 
  array (
    0 => 'yaf-request-abstract.isrouted.php',
    1 => 'Yaf_Request_Abstract::isRouted',
  ),
  20 => 
  array (
    0 => 'yaf-request-abstract.isxmlhttprequest.php',
    1 => 'Yaf_Request_Abstract::isXmlHttpRequest',
  ),
  21 => 
  array (
    0 => 'yaf-request-abstract.setactionname.php',
    1 => 'Yaf_Request_Abstract::setActionName',
  ),
  22 => 
  array (
    0 => 'yaf-request-abstract.setbaseuri.php',
    1 => 'Yaf_Request_Abstract::setBaseUri',
  ),
  23 => 
  array (
    0 => 'yaf-request-abstract.setcontrollername.php',
    1 => 'Yaf_Request_Abstract::setControllerName',
  ),
  24 => 
  array (
    0 => 'yaf-request-abstract.setdispatched.php',
    1 => 'Yaf_Request_Abstract::setDispatched',
  ),
  25 => 
  array (
    0 => 'yaf-request-abstract.setmodulename.php',
    1 => 'Yaf_Request_Abstract::setModuleName',
  ),
  26 => 
  array (
    0 => 'yaf-request-abstract.setparam.php',
    1 => 'Yaf_Request_Abstract::setParam',
  ),
  27 => 
  array (
    0 => 'yaf-request-abstract.setrequesturi.php',
    1 => 'Yaf_Request_Abstract::setRequestUri',
  ),
  28 => 
  array (
    0 => 'yaf-request-abstract.setrouted.php',
    1 => 'Yaf_Request_Abstract::setRouted',
  ),
);
$PARENTS = array (
  0 => 
  array (
    0 => 'book.yaf.php',
    1 => 'Yaf',
  ),
);